import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Timestamp;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Remy
 */
public class AskQuestion extends javax.swing.JFrame {

    /**
     * Creates new form AskQuestion
     */
    public AskQuestion() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        que_preview = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        que_title = new javax.swing.JTextArea();
        ask_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        que_body = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        que_preview.setEditable(false);
        que_preview.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        que_preview.setContentType("text/html"); // NOI18N
        que_preview.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        jScrollPane3.setViewportView(que_preview);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 430, 420));

        que_title.setColumns(20);
        que_title.setFont(new java.awt.Font("Leelawadee UI", 0, 15)); // NOI18N
        que_title.setLineWrap(true);
        que_title.setRows(3);
        que_title.setWrapStyleWord(true);
        que_title.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        que_title.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                que_titleCaretUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(que_title);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 460, 80));

        ask_btn.setFont(new java.awt.Font("Cambria Math", 0, 20)); // NOI18N
        ask_btn.setText("Ask");
        ask_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ask_btnActionPerformed(evt);
            }
        });
        getContentPane().add(ask_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 90, 30));

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PREVIEW");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 410, 40));

        jLabel2.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ASK QUESTIONS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 460, 40));

        que_body.setColumns(20);
        que_body.setFont(new java.awt.Font("Leelawadee UI", 0, 15)); // NOI18N
        que_body.setLineWrap(true);
        que_body.setRows(5);
        que_body.setWrapStyleWord(true);
        que_body.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        que_body.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                que_bodyCaretUpdate(evt);
            }
        });
        jScrollPane2.setViewportView(que_body);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 460, 300));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Cambria Math", 0, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("<html>&times;</html>");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setMargin(new java.awt.Insets(2, 0, 14, 6));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3close(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 50, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Question Body");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Question Title");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gradient-blue-green-hd-wallpaper.jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ask_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ask_btnActionPerformed
        // Validation
        String queTitle = que_title.getText().trim();
        String queBody = que_body.getText().trim();
        if(!queTitle.isEmpty() && !queBody.isEmpty()) {
            if(queTitle.length()>30 && queBody.length()>50) {
        Date d = new Date();
        Timestamp t = new Timestamp(d.getTime());
        String date = t.toString().substring(0, 19);

        try {
            Class.forName("java.sql.DriverManager");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/qAnda", "root", "");
            String q = "insert into questions (user_id, que_title, que_body, date) values(?,?,?,?)";
            PreparedStatement ps = conn.prepareStatement(q);
            ps.setInt(1, Login.currentUserLoggedIn);
            ps.setString(2, queTitle);
            ps.setString(3, queBody);
            ps.setString(4, date);
            ps.executeUpdate();

            ps.close();
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        new Home().setVisible(true);
        dispose();
            } else {
                JOptionPane.showMessageDialog(this, "<html>Question title and Question body must contain<br/>"
                        + " more than 30 and 50 characters respectively!</html>");
            }
        } else {
         JOptionPane.showMessageDialog(this, "Either question title or question body is not specified!");
        }
    }//GEN-LAST:event_ask_btnActionPerformed

    private void que_titleCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_que_titleCaretUpdate
        que_preview.setText("<html>"
                + "<body>"
                + "<h3>" + que_title.getText() + "</h3>"
                + "<hr/>"
                + que_body.getText()
                + "</body>"
                + "</html>");
    }//GEN-LAST:event_que_titleCaretUpdate

    private void que_bodyCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_que_bodyCaretUpdate
        que_preview.setText("<html>"
                + "<body>"
                + "<h3>" + que_title.getText() + "</h3>"
                + "<hr/>"
                + que_body.getText()
                + "</body>"
                + "</html>");
    }//GEN-LAST:event_que_bodyCaretUpdate

    private void jButton3close(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3close
        dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_jButton3close

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AskQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AskQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AskQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AskQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AskQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ask_btn;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea que_body;
    private javax.swing.JTextPane que_preview;
    private javax.swing.JTextArea que_title;
    // End of variables declaration//GEN-END:variables
}
