
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Timestamp;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Remy
 */
public class GiveAnswer extends javax.swing.JFrame {

    /**
     * Creates new form GiveAnswer
     */
    public GiveAnswer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        ansBody = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ansPreview = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        add_btn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ansBody.setColumns(20);
        ansBody.setFont(new java.awt.Font("Leelawadee UI", 0, 15)); // NOI18N
        ansBody.setLineWrap(true);
        ansBody.setRows(5);
        ansBody.setWrapStyleWord(true);
        ansBody.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ansBody.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                ansBodyCaretUpdate(evt);
            }
        });
        jScrollPane2.setViewportView(ansBody);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 440, 460));

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PREVIEW");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 440, 30));

        ansPreview.setEditable(false);
        ansPreview.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ansPreview.setContentType("text/html"); // NOI18N
        ansPreview.setFont(new java.awt.Font("Leelawadee UI", 0, 15)); // NOI18N
        jScrollPane3.setViewportView(ansPreview);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 450, 460));

        jLabel2.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("YOUR ANSWER");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 480, 30));

        add_btn.setFont(new java.awt.Font("Cambria Math", 0, 20)); // NOI18N
        add_btn.setText("Add");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });
        getContentPane().add(add_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 90, 30));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Cambria Math", 0, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("<html>&times;</html>");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setMargin(new java.awt.Insets(2, 0, 14, 6));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3close(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 50, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gradient-blue-green-hd-wallpaper.jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        //validation
        String answer = ansBody.getText().trim();
        if (!answer.isEmpty()) {
            //if it is less than 50 characters
            if (answer.length() > 50) {
                Date d = new Date();
                Timestamp t = new Timestamp(d.getTime());
                String date = t.toString().substring(0, 19);
                try {
                    Class.forName("java.sql.DriverManager");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/qAnda", "root", "");
                    String q = "insert into answers (que_id, user_id, ans_body, date) values(?,?,?,?)";
                    PreparedStatement ps = conn.prepareStatement(q);
                    ps.setInt(1, Home.currentQuestionId);
                    ps.setInt(2, Login.currentUserLoggedIn);
                    ps.setString(3, answer);
                    ps.setString(4, date);
                    ps.executeUpdate();
                    ps.close();
                    conn.close();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
                //Answer is added to the table and opening the QWA frame 
                // disposing the current one
                new QuestionWithAnswers().setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Please add more than 50 characters to your answer.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Answer can't be empty");
        }
    }//GEN-LAST:event_add_btnActionPerformed

    private void ansBodyCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_ansBodyCaretUpdate
        ansPreview.setText("<html>"
                + "<body>"
                + ansBody.getText()
                + "</body>"
                + "</html>");
    }//GEN-LAST:event_ansBodyCaretUpdate

    private void jButton3close(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3close
        dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_jButton3close

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiveAnswer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiveAnswer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiveAnswer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiveAnswer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiveAnswer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JTextArea ansBody;
    private javax.swing.JTextPane ansPreview;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
