import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author jetking computers
 */
public class UserProfile extends javax.swing.JFrame {

    public static boolean QUESTIONS_OF_USERPROFILE_CLICKED = false;

    /**
     * Creates new form UserProfile
     */
    public UserProfile() {
        initComponents();

        //form window opened
        try {
            Class.forName("java.sql.DriverManager");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/qAnda", "root", "");
            String q = "select que_id, que_title from questions where user_id = ? order by date";
            String q1 = "select que_id, que_title from questions join answers using(que_id) where answers.user_id = ? order by answers.date desc";
            String q2 = "select user_name from users where user_id = ?";
            PreparedStatement ps = conn.prepareStatement(q);
            PreparedStatement ps1 = conn.prepareStatement(q1);
            PreparedStatement ps2 = conn.prepareStatement(q2);
            ps.setInt(1, Login.currentUserLoggedIn);
            ps1.setInt(1, Login.currentUserLoggedIn);
            ps2.setInt(1, Login.currentUserLoggedIn);
            ResultSet rs = ps.executeQuery();
            ResultSet rs1 = ps1.executeQuery();
            ResultSet rs2 = ps2.executeQuery();

            //serializing variable;;;
            int i = 1;
            while (rs.next()) {
                JLabel que = new JLabel(" " + i + ". " + rs.getString(2));
                que.setFont(new java.awt.Font("Georgia", 300, 16));
                //setting name
                que.setName(rs.getString(1));
                //when label will be clicked.. redirecting the user to QuestionWithAnswers
                que.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        dispose();
                        UserProfile.QUESTIONS_OF_USERPROFILE_CLICKED = true;
                        new QuestionWithAnswers().setVisible(true);
                        Home.currentQuestionId = Integer.parseInt(evt.getComponent().getName());
                    }
                });
                userQuestions.add(que);
                i++;
            }
            i = 1;
            while (rs1.next()) {
                JLabel ans = new JLabel(" " + i + ". " + rs1.getString(2));
                ans.setFont(new java.awt.Font("Georgia", 300, 16));
                
                ans.setName(rs1.getString(1));
                //when label will be clicked.. redirecting the user to QuestionWithAnswers
                ans.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        dispose();
                        UserProfile.QUESTIONS_OF_USERPROFILE_CLICKED = true;
                        new QuestionWithAnswers().setVisible(true);
                        Home.currentQuestionId = Integer.parseInt(evt.getComponent().getName());
                    }
                });
                
                userAnswers.add(ans);
                i++;
            }
            userQuestions.revalidate();
            userAnswers.revalidate();

            //showing user name who is logged in.
            rs2.next();
            header.setText("Hi, " + rs2.getString(1));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userQuestions = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        userAnswers = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        close_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Questions Asked");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 160, -1));

        userQuestions.setBackground(new java.awt.Color(255, 255, 255));
        userQuestions.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userQuestions.setLayout(new java.awt.GridLayout(0, 1, 0, 2));
        jScrollPane1.setViewportView(userQuestions);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 610, 240));

        jLabel2.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Answers given");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 150, -1));

        userAnswers.setBackground(new java.awt.Color(255, 255, 255));
        userAnswers.setLayout(new java.awt.GridLayout(3, 1, 0, 5));
        jScrollPane2.setViewportView(userAnswers);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 610, 260));

        header.setFont(new java.awt.Font("Cambria Math", 0, 36)); // NOI18N
        header.setForeground(new java.awt.Color(255, 255, 255));
        header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 559, 50));

        close_btn.setBackground(new java.awt.Color(255, 0, 0));
        close_btn.setFont(new java.awt.Font("Cambria Math", 0, 36)); // NOI18N
        close_btn.setForeground(new java.awt.Color(255, 255, 255));
        close_btn.setText("<html>&times;</html>");
        close_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        close_btn.setMargin(new java.awt.Insets(2, 0, 14, 6));
        close_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_btnclose(evt);
            }
        });
        getContentPane().add(close_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 50, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gradient.jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void close_btnclose(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_btnclose
        dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_close_btnclose

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close_btn;
    private javax.swing.JLabel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel userAnswers;
    private javax.swing.JPanel userQuestions;
    // End of variables declaration//GEN-END:variables
}
